export { default as MainNews } from "./MainNews"
export { default as Deadlines } from "./Deadlines"
export { default as MarkingProducts } from "./MarkingProducts"
export { default as StartTutorial } from "./StartTutorial"
export { default as SystemDocuments } from "./SystemDocuments"
